
import { FileText, ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';

export const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="flex-1 overflow-y-auto p-4 space-y-6">
      <div className="card-glass">
        <div className="flex items-center space-x-4 mb-6">
          <Button variant="ghost" size="sm" onClick={() => navigate(-1)}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-gradient-to-r from-green-600 to-blue-600 rounded-xl flex items-center justify-center">
              <FileText className="h-5 w-5 text-white" />
            </div>
            <h1 className="text-2xl font-bold">Terms of Service</h1>
          </div>
        </div>

        <div className="space-y-6 text-sm text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Acceptance of Terms</h2>
            <p>By using VidRanker, you agree to these Terms of Service. If you do not agree, please do not use our services.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Service Description</h2>
            <p>VidRanker is an AI-powered tool that helps YouTube content creators optimize their videos through:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>SEO content generation (titles, descriptions, tags, hashtags)</li>
              <li>Thumbnail creation and optimization</li>
              <li>Content history management</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">User Responsibilities</h2>
            <p>You are responsible for:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Providing accurate information when using our services</li>
              <li>Complying with YouTube's Terms of Service and Community Guidelines</li>
              <li>Using generated content appropriately and legally</li>
              <li>Not using the service for spam or malicious purposes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Intellectual Property</h2>
            <p>Content generated by VidRanker using your input belongs to you. However, we retain rights to our AI technology and software.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Limitation of Liability</h2>
            <p>VidRanker is provided "as is" without warranties. We are not liable for any damages arising from your use of our services.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Contact</h2>
            <p>For terms-related questions, contact us at: legal@vidranker.com</p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
